"""Add completion_date to Transaction model

Revision ID: 98571d755ff8
Revises: f5efeed08e55
Create Date: 2025-07-09 14:58:39.303030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98571d755ff8'
down_revision: Union[str, Sequence[str], None] = 'f5efeed08e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('completion_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'completion_date')
    # ### end Alembic commands ###
